"""add Numeric

Revision ID: 5e8b6e1515f8
Revises: 
Create Date: 2020-03-07 18:21:22.396783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8b6e1515f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_type', sa.String(length=120), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=True),
    sa.Column('value', sa.String(length=3000), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('scheduled', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=10), nullable=True),
    sa.Column('floaty', sa.Float(), nullable=True),
    sa.Column('deci', sa.Numeric(precision=2), nullable=True),
    sa.Column('splitter', sa.String(length=122), nullable=True),
    sa.Column('zero', sa.String(length=123), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_key'), 'setting', ['key'], unique=False)
    op.create_index(op.f('ix_setting_setting_type'), 'setting', ['setting_type'], unique=False)
    op.create_index(op.f('ix_setting_splitter'), 'setting', ['splitter'], unique=False)
    op.create_table('sub_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('sub_updated', sa.DateTime(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.Column('flong', sa.String(length=120), nullable=True),
    sa.Column('boolean', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_setting_flong'), 'sub_setting', ['flong'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_setting_flong'), table_name='sub_setting')
    op.drop_table('sub_setting')
    op.drop_index(op.f('ix_setting_splitter'), table_name='setting')
    op.drop_index(op.f('ix_setting_setting_type'), table_name='setting')
    op.drop_index(op.f('ix_setting_key'), table_name='setting')
    op.drop_table('setting')
    op.drop_table('bad_model')
    # ### end Alembic commands ###
