"""change to LargeBinary

Revision ID: 7002ab7a4dea
Revises: 5e8b6e1515f8
Create Date: 2020-03-07 21:25:08.200324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7002ab7a4dea'
down_revision = '5e8b6e1515f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('lob', sa.LargeBinary(), nullable=True))
    op.drop_index('ix_setting_splitter', table_name='setting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('zero', sa.VARCHAR(length=123), nullable=True))
    op.add_column('setting', sa.Column('splitter', sa.VARCHAR(length=122), nullable=True))
    op.create_index('ix_setting_splitter', 'setting', ['splitter'], unique=False)
    op.drop_column('setting', 'lob')
    # ### end Alembic commands ###
